#!/usr/bin/env bash
set -u

ROOT="${1:-.}"
cd "$ROOT" || exit 2
errors=0
warnings=0
ok() { printf 'OK   %s\n' "$1"; }
warn() { printf 'WARN %s\n' "$1"; warnings=$((warnings + 1)); }
fail() { printf 'FAIL %s\n' "$1"; errors=$((errors + 1)); }

[[ -d .git ]] && ok "Git repository detected" || warn "Not a Git repository"
project_files=$(find . -maxdepth 5 \( -name '*.xcodeproj' -o -name '*.xcworkspace' \) -print 2>/dev/null)
[[ -n "$project_files" ]] && ok "Xcode project/workspace detected" || fail "No .xcodeproj or .xcworkspace found"

if [[ -f Info.plist ]]; then plist=Info.plist
elif [[ -n "$project_files" ]]; then plist=$(find . -name Info.plist -print -quit)
else plist=""; fi
if [[ -n "$plist" ]]; then
  ok "Info.plist found: $plist"
  if command -v /usr/libexec/PlistBuddy >/dev/null 2>&1; then
    bundle=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$plist" 2>/dev/null || true)
    version=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$plist" 2>/dev/null || true)
    build=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$plist" 2>/dev/null || true)
    [[ -n "$bundle" ]] && ok "Bundle identifier: $bundle" || fail "CFBundleIdentifier is missing"
    [[ -n "$version" ]] && ok "Marketing version: $version" || warn "CFBundleShortVersionString is missing or generated"
    [[ -n "$build" ]] && ok "Build number: $build" || warn "CFBundleVersion is missing or generated"
  else
    warn "PlistBuddy unavailable; could not inspect Info.plist values"
  fi
else
  warn "Info.plist not found directly; values may be generated by Xcode"
fi

if rg -q 'get-task-allow.*true|CODE_SIGN_INJECT_BASE_ENTITLEMENTS.*YES' . --glob '!*.xcuserstate' --glob '!Pods/**' 2>/dev/null; then
  fail "Development signing entitlement appears in repository configuration"
else
  ok "No obvious development signing entitlement found"
fi

for f in PrivacyInfo.xcprivacy ExportOptions.plist; do
  if find . -name "$f" -print -quit | grep -q .; then ok "$f found"; else warn "$f not found (confirm whether it is required)"; fi
done

for url in $(rg -o 'https?://[^ )"<>]+' README.md references templates 2>/dev/null | sed 's/[),.]$//' | sort -u); do
  if command -v curl >/dev/null 2>&1; then
    code=$(curl -L -k -s -o /dev/null -w '%{http_code}' --max-time 10 "$url" || true)
    [[ "$code" =~ ^2|^3 ]] && ok "URL reachable: $url ($code)" || warn "URL check failed: $url ($code)"
  fi
done

printf '\nSummary: %d error(s), %d warning(s)\n' "$errors" "$warnings"
[[ "$errors" -eq 0 ]] || exit 1
